### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by rickspencer3** [InfluxCommunity/ricks-downsampler#1]
# P0
- [ ] Schedule tasks by minute, hour, or days
- [ ] Accept user input for source data
- [ ] Create a query by querying for schema
- [ ] Write data back to target database
- [ ] Build docker container and push to registry
- [ ] Test for multiple days in AWS

# P1
- [ ] Log task runs
- [ ] Accept INCLUDE_FIELDS
- [ ] Accepted EXCLUDE_FIELDS
- [ ] Allow user to provide alternate aggregate function
- [ ] Allow user to provide aggregate function per field
- [ ] Accept INCLUDE_TAGS
- [ ] Accept EXCLUDE_TAGS
- [ ] Accept TAG_VALUES (dictionary like {tag_key:[tag_vals]}
- [ ] Handle retries

#P2
- [ ] Option to  forget schema (allows downsampling to adapt to new schema)
- [ ] Option for setting task_id for logs
- [ ] Option for quiet logging (only log on startup and errors
- [ ] Allow user to supply customer InfluxQL or SQL
